server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dilshan93/config-server-demo
          search-paths:
            - 'server-config/*service'
